# Default build settings

language: c++
compiler: g++
os: linux
# fast_finish: true
notifications:
    slack: frupal-dev:EqKuho9NXtDZzAyzMpRTr1pM

branches:
    only:
        - master
        - stable
        - dmitri-dev

pre-install: ./pre-install.sh
install: make test

script: tests/ALL_TESTS
